server:
  port: 8060
  ssl:
    enabled: false

spring:
  # kafka
  kafka:
    consumer:
      properties:
        spring.json.trusted.packages: "*"
      bootstrap-servers: localhost:9092
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: Manual

# log level setting
logging:
  level:
    root: info
    com:
      ssafy: debug

# feign
feign:
  hystrix:
    enabled: true
