variables:
  VERCEL_TOKEN: "gwYQqIF7NXKrB8EJiRjH0OLx"

default:
  image: node:16.16.0

deploy_preview:
  stage: deploy
  except:
    - master
  script:
    - cd front
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - yarn config delete proxy
    - yarn config delete https-proxy
    - yarn install --network-timeout 600000
    - vercel build --token=$VERCEL_TOKEN
deploy_production:
  stage: deploy
  only:
    - master
  script:
    - cd front
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
