variables:
  VERCEL_TOKEN: "gwYQqIF7NXKrB8EJiRjH0OLx"

default:
  image: node:18.13.0

deploy_preview:
  stage: deploy
  except:
    - master
    - develop-fe
  script:
    - cd front
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt  --token=$VERCEL_TOKEN
deploy_production:
  stage: deploy
  only:
    - master
    - develop-fe
  script:
    - cd front
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN