server:
  port: 8050

# log level setting
logging:
  level:
    root: info
    com:
      ssafy: debug
  #redis
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    url: redis://localhost:6379
# feign
feign:
  hystrix:
    enabled: true