server:
  port: 5000
  ssl:
    enabled: false

# openvidu
OPENVIDU_URL: http://http://i8b302.p.ssafy.io:4443/
OPENVIDU_SECRET: ssafy

# log level setting
logging:
  level:
    root: info
    com:
      ssafy: debug
