
spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssarijileo?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
  # JPA Properties
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # application-oauth
  profiles:
    include: oauth

# log level setting
logging:
  level:
    root: info
    com:
      ssafy: debug
#    org:
#      springframework:
#        security:
#          web: debug

# jwt SsarijileoSecretKey 20 Fin
#jwt:
#  header: Authorization
#  secret: U3NhcmlqaWxlb1NlY3JldEtleVNzYXJpamlsZW9TZWNyZXRLZXlTc2FyaWppbGVvU2VjcmV0S2V5U3NhcmlqaWxlb1NlY3JldEtleVNzYXJpamlsZW9TZWNyZXRLZXlTc2FyaWppbGVvU2VjcmV0S2V5U3NhcmlqaWxlb1NlY3JldEtleVNzYXJpamlsZW9TZWNyZXRLZXlTc2FyaWppbGVvU2VjcmV0S2V5U3NhcmlqaWxlb1NlY3JldEtleVNzYXJpamlsZW9TZWNyZXRLZXlTc2FyaWppbGVvU2VjcmV0S2V5U3NhcmlqaWxlb1NlY3JldEtleVNzYXJpamlsZW9TZWNyZXRLZXlTc2FyaWppbGVvU2VjcmV0S2V5U3NhcmlqaWxlb1NlY3JldEtleVNzYXJpamlsZW9TZWNyZXRLZXlTc2FyaWppbGVvU2VjcmV0S2V5U3NhcmlqaWxlb1NlY3JldEtleVNzYXJpamlsZW9TZWNyZXRLZXlGaW4=
#  token-validity-in-seconds: 86400

