version: "1"
services:
  # mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  # zookeeper
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  #kafka
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # redis
  predixy:
    image: haandol/predixy
    container_name: predixy
    hostname: predixy
    build:
      context: /predixy
    volumes:
      - ./predixy/conf:/etc/predixy/conf
    ports:
      - "127.0.0.1:7300:7300"
  redis-session:
    image: redis:latest
    container_name: redis-session
    volumes:
      - ./redis-session.conf:/usr/local/etc/redis-session.conf
      - ./start.sh:/start.sh
    command: redis-server /usr/local/etc/redis-session.conf
    ports:
      - "127.0.0.1:6379:6379"
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
    ports:
      - "127.0.0.1:6389:6389"
  redis-auth:
    image: redis:latest
    container_name: redis-auth
    volumes:
      - ./redis-auth.conf:/usr/local/etc/redis-auth.conf
    command: redis-server /usr/local/etc/redis-auth.conf
    ports:
      - "127.0.0.1:6399:6399"
  redis-session-slave:
    image: redis:latest
    container_name: redis-session-slave
    volumes:
      - ./redis-session-slave.conf:/usr/local/etc/redis-session-slave.conf
    command: redis-server /usr/local/etc/redis-session-slave.conf
    ports:
      - 127.0.0.1:6479:6479
  redis-slave:
    image: redis:latest
    container_name: redis-slave
    volumes:
      - ./redis-slave.conf:/usr/local/etc/redis-slave.conf
    command: redis-server /usr/local/etc/redis-slave.conf
    ports:
      - "127.0.0.1:6489:6489"
  redis-auth-slave:
    image: redis:latest
    container_name: redis-auth-slave
    volumes:
      - ./redis-auth-slave.conf:/usr/local/etc/redis-auth-slave.conf
    command: redis-server /usr/local/etc/redis-auth-slave.conf
    ports:
      - "127.0.0.1:6499:6499"

networks:
  redis-net:
    driver: bridge
