server:
  port: 8000

spring:
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # application-oauth
  profiles:
    include: oauth

# log level setting
logging:
  level:
    root: info
    com:
      ssafy: debug

