version: "1"

services:
  # mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # zookeeper
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  #kafka
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # redis
  redis:
    container_name: redis
    image: redis
    command: redis-server --port 6379
    ports:
      - 6379:6379

  # openvidu
  openvidu:
    container_name: openvidu
    image: openvidu/openvidu-dev:2.25.0
    restart: on-failure
    environment:
      - OPENVIDU_SECRET=ssafy
    ports:
      - 4443:4443
