server:
    port: 8070
    ssl:
        enabled: false

spring:
    # Redis
    redis:
        host: http://i8b302.p.ssafy.io/
        port: 6379
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1
